# Generated by Django 4.0.4 on 2022-05-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], max_length=32)),
                ('description', models.CharField(blank=True, max_length=4096, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='camps/')),
            ],
        ),
    ]
