# Generated by Django 4.0.4 on 2022-05-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campmodel',
            name='picture',
            field=models.ImageField(null=True, upload_to='camps'),
        ),
    ]
