# Generated by Django 4.0.4 on 2022-05-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0002_campmodel_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campmodel',
            name='description',
            field=models.CharField(default=None, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='campmodel',
            name='picture',
            field=models.ImageField(null=True, upload_to='camps/'),
        ),
        migrations.AlterField(
            model_name='campmodel',
            name='type',
            field=models.CharField(choices=[('HYBRID', 'гибридная смена'), ('ONLINE', 'онлайн смена'), ('OFFLINE', 'оффлайн смена')], max_length=32),
        ),
    ]
